theme: jekyll-theme-merlot
show_downloads: true
title: Imperialism 2 Savegame editor
github:
  zip_url: https://github.com/Reken41/Imperialism2_SGEditor/releases/download/v0.1.0.0/Imperialism.2.SGEditor.v0.1.exe.zip
